In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [45]:
dataframe = pd.read_csv('../Datasets/Fish.csv')
dataframe.head(10)

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
5   Bream   450.0     26.8     29.7     34.7  13.6024  4.9274
6   Bream   500.0     26.8     29.7     34.5  14.1795  5.2785
7   Bream   390.0     27.6     30.0     35.0  12.6700  4.6900
8   Bream   450.0     27.6     30.0     35.1  14.0049  4.8438
9   Bream   500.0     28.5     30.7     36.2  14.2266  4.9594

In [46]:
dataframe.isna().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [47]:
dataframe.shape

(159, 7)

In [50]:
x = dataframe['Species'].unique()
x

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [51]:
df1 = dataframe
df1['Species'] = pd.factorize(dataframe['Species'])[0]

In [64]:
X = df1.iloc[:,1:]
y = df1.iloc[:,0]
print(X.shape)
print(y.shape)
print(y.iloc[157])

(159, 6)
(159,)
6


In [65]:
from sklearn.utils import shuffle 

X, y = shuffle(X, y)

In [66]:

scaler = MinMaxScaler(feature_range=(0,1))
X_scaled = scaler.fit_transform(X)
print(X_scaled.shape)
for i in range(0,5):
    print(X_scaled[i])

(159, 6)
[0.15757576 0.34757282 0.34727273 0.33952703 0.31568439 0.46337957]
[0.00454545 0.04854369 0.03818182 0.0472973  0.01413928 0.01584348]
[0.60606061 0.63495146 0.63818182 0.62837838 0.63125268 1.        ]
[0.00357576 0.         0.         0.         0.0222653  0.05080063]
[0.3030303  0.66990291 0.66545455 0.66216216 0.30365787 0.54245602]


In [73]:
model = Sequential([
    Dense(units=20, input_shape=(6,), activation='relu'),
    Dense(units=10, activation='relu'),
    Dense(units=7, activation='softmax')
])

In [74]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [77]:
model.fit(x=X_scaled,y=y,batch_size=10,epochs=30,verbose=2)

Epoch 1/30
16/16 - 0s - loss: 1.6516 - accuracy: 0.2264 - 41ms/epoch - 3ms/step
Epoch 2/30
16/16 - 0s - loss: 1.6499 - accuracy: 0.2264 - 37ms/epoch - 2ms/step
Epoch 3/30
16/16 - 0s - loss: 1.6481 - accuracy: 0.2327 - 43ms/epoch - 3ms/step
Epoch 4/30
16/16 - 0s - loss: 1.6465 - accuracy: 0.2327 - 46ms/epoch - 3ms/step
Epoch 5/30
16/16 - 0s - loss: 1.6447 - accuracy: 0.2390 - 42ms/epoch - 3ms/step
Epoch 6/30
16/16 - 0s - loss: 1.6430 - accuracy: 0.2390 - 45ms/epoch - 3ms/step
Epoch 7/30
16/16 - 0s - loss: 1.6413 - accuracy: 0.2390 - 50ms/epoch - 3ms/step
Epoch 8/30
16/16 - 0s - loss: 1.6396 - accuracy: 0.2516 - 44ms/epoch - 3ms/step
Epoch 9/30
16/16 - 0s - loss: 1.6380 - accuracy: 0.2516 - 50ms/epoch - 3ms/step
Epoch 10/30
16/16 - 0s - loss: 1.6363 - accuracy: 0.2579 - 35ms/epoch - 2ms/step
Epoch 11/30
16/16 - 0s - loss: 1.6348 - accuracy: 0.2642 - 39ms/epoch - 2ms/step
Epoch 12/30
16/16 - 0s - loss: 1.6331 - accuracy: 0.2642 - 34ms/epoch - 2ms/step
Epoch 13/30
16/16 - 0s - loss: 1.6315

#### Using validation split

In [78]:
model.fit(x=X_scaled,y=y,validation_split=0.2,batch_size=10,epochs=30,verbose=2)

Epoch 1/30
13/13 - 0s - loss: 1.5828 - accuracy: 0.4331 - val_loss: 1.6797 - val_accuracy: 0.4688 - 292ms/epoch - 22ms/step
Epoch 2/30
13/13 - 0s - loss: 1.5813 - accuracy: 0.4331 - val_loss: 1.6786 - val_accuracy: 0.4688 - 86ms/epoch - 7ms/step
Epoch 3/30
13/13 - 0s - loss: 1.5798 - accuracy: 0.4409 - val_loss: 1.6775 - val_accuracy: 0.4688 - 85ms/epoch - 7ms/step
Epoch 4/30
13/13 - 0s - loss: 1.5783 - accuracy: 0.4409 - val_loss: 1.6764 - val_accuracy: 0.5000 - 78ms/epoch - 6ms/step
Epoch 5/30
13/13 - 0s - loss: 1.5768 - accuracy: 0.4409 - val_loss: 1.6752 - val_accuracy: 0.5000 - 85ms/epoch - 7ms/step
Epoch 6/30
13/13 - 0s - loss: 1.5754 - accuracy: 0.4409 - val_loss: 1.6743 - val_accuracy: 0.5000 - 79ms/epoch - 6ms/step
Epoch 7/30
13/13 - 0s - loss: 1.5739 - accuracy: 0.4409 - val_loss: 1.6732 - val_accuracy: 0.5000 - 73ms/epoch - 6ms/step
Epoch 8/30
13/13 - 0s - loss: 1.5726 - accuracy: 0.4409 - val_loss: 1.6722 - val_accuracy: 0.5000 - 96ms/epoch - 7ms/step
Epoch 9/30
13/13 - 0s 

#### Using validation test set

In [79]:
from sklearn.model_selection import train_test_split

X_train_scaled, X_test_scaled, y_train, y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=42)



In [80]:
model.fit(x=X_train_scaled,y=y_train,batch_size=10,epochs=30,verbose=2)

Epoch 1/30
13/13 - 0s - loss: 1.5544 - accuracy: 0.4961 - 37ms/epoch - 3ms/step
Epoch 2/30
13/13 - 0s - loss: 1.5531 - accuracy: 0.4961 - 28ms/epoch - 2ms/step
Epoch 3/30
13/13 - 0s - loss: 1.5517 - accuracy: 0.4961 - 36ms/epoch - 3ms/step
Epoch 4/30
13/13 - 0s - loss: 1.5504 - accuracy: 0.4961 - 45ms/epoch - 3ms/step
Epoch 5/30
13/13 - 0s - loss: 1.5491 - accuracy: 0.5039 - 40ms/epoch - 3ms/step
Epoch 6/30
13/13 - 0s - loss: 1.5478 - accuracy: 0.5039 - 59ms/epoch - 5ms/step
Epoch 7/30
13/13 - 0s - loss: 1.5465 - accuracy: 0.5118 - 45ms/epoch - 3ms/step
Epoch 8/30
13/13 - 0s - loss: 1.5451 - accuracy: 0.5197 - 27ms/epoch - 2ms/step
Epoch 9/30
13/13 - 0s - loss: 1.5439 - accuracy: 0.5276 - 29ms/epoch - 2ms/step
Epoch 10/30
13/13 - 0s - loss: 1.5426 - accuracy: 0.5197 - 23ms/epoch - 2ms/step
Epoch 11/30
13/13 - 0s - loss: 1.5412 - accuracy: 0.5276 - 37ms/epoch - 3ms/step
Epoch 12/30
13/13 - 0s - loss: 1.5398 - accuracy: 0.5276 - 43ms/epoch - 3ms/step
Epoch 13/30
13/13 - 0s - loss: 1.5385

In [83]:
y_pred = model.predict(X_test_scaled,batch_size=10,verbose=0)

In [84]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true=y_test,y_pred=y_pred)

ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets